export const SET_TEMPERATURES_BY_DAY = "SET_TEMPERATURES_BY_DAY";
export const SET_TEMPERATURES_BY_HOUR = "SET_TEMPERATURES_BY_HOUR";

export const SET_WEEKLY_AVERAGE = "SET_WEEKLY_AVERAGE";

export const LOADED = "LOADED";

export const ERRORS = {
    NO_CITY_FOUND: "NO_CITY_FOUND"
}
